import os
import sys


def generate_tfvars_shell(tf_vars_location: str):
    # Helper function to generate TF_VAR environment variables from an existing .tfvars file
    with open(tf_vars_location, 'r') as vars_file:
        content = vars_file.readlines()

    vars_shell_location = f"{tf_vars_location}.sh"

    if os.path.exists(vars_shell_location):
        os.remove(vars_shell_location)  # We always want to overwrite the tfvars file if it exists

    with open(vars_shell_location, "w") as vars_shell:
        vars_shell.write("#!/usr/bin/env bash\n")
        vars_shell.write("# Autogenerated script to export content of terraform.tfvars file as global env vars\n\n")

        for line in content:
            if line[0] == "#" or line[0] == '\n':
                continue  # Ignore lines that start with a comment or blank

            var_tokens = line.strip().replace('"', '').replace(" ", "").split("=")  # Strip spaces from candidate lines
            print(var_tokens)

            vars_shell.write(f"export TF_VAR_{var_tokens[0]}={var_tokens[1]}\n")


if __name__ == "__main__":
    tfvars_location = sys.argv[1]
    generate_tfvars_shell(tfvars_location)